#!/bin/sh
# 
# The MIT License (MIT)
# 
# Copyright (c) 2015 Jeffrey Hutchins
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 

git stash >> /dev/null 2>&1
git pull --rebase >> /dev/null 2>&1
if [ $? -gt 0 ]
then
    GIT_PROXY=/tmp/git
    GIT=$(which git)
    OLD_PATH=$PATH
    PATH=$(dirname $GIT_PROXY):$PATH

    cat > $GIT_PROXY <<DONE
#!/bin/bash
echo "run $GIT \$@"
$GIT \$@
if [ \$? -eq 0 ] && [ \$1 == "rebase" ]
then
    ps -ef | grep \$\$ | awk '{print \$3}' | head -n 1 | xargs kill -9
fi
DONE

    chmod +x $GIT_PROXY

    echo
    echo "There was an conflict with the rebase. The git status will now be shown to you"
    echo "and you will be given an oppurtunity to resolve issues."
    echo
    echo "When you are finished resolving issues the change will be pushed"
    echo
    echo "Press 'Enter' to proceed"
    echo

    read

    git status
    $SHELL
    rm $GIT_PROXY
    PATH=$OLD_PATH
fi
git push
git stash pop >> /dev/null 2>&1
exit 0
